# Generated by Django 4.2 on 2023-06-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='polis',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
