# Generated by Django 4.2 on 2023-06-02 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_appointment'),
        ('users', '0006_profile_address_profile_date_of_birth_profile_diet_and_more'),
    ]

    operations = [
    ]
