# Generated by Django 4.2 on 2023-06-09 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_diet_purchasehistory_recipe_diet_recipes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('product_norm', models.CharField(max_length=255)),
                ('brand_norm', models.CharField(blank=True, max_length=255, null=True)),
                ('cat_norm', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
